name: release

on:
  push:
    branches:
    - main

env:
  AWS_REGION: us-west-2
  AWS_ROLE: arn:aws:iam::270074865685:role/terraform-module-ci-test
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions: {}

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 240 # 4 hours
    steps:
      - name: 'Release Please'
        # https://github.com/googleapis/release-please-action/releases
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release-please
        with:
          release-type: terraform-module

      - name: 'Checkout'
        if: steps.release-please.outputs.pr
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: 'Free Disk Space Before Test'
        if: steps.release-please.outputs.pr
        shell: bash
        run: |
          bash .github/workflows/scripts/free-disk-space.sh

      - name: 'Comment PR e2e wait'
        if: steps.release-please.outputs.pr
        # https://github.com/actions/github-script/releases
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const scriptPath = `${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/pr-e2e-wait.js`;
            const { default: script } = await import(scriptPath);
            context.payload.pull_request = { number: ${{ fromJson(steps.release-please.outputs.pr).number }} };
            await script({ github, context });

      - name: 'Configure AWS Credentials'
        if: steps.release-please.outputs.pr
        # https://github.com/aws-actions/configure-aws-credentials/releases
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: ${{env.AWS_ROLE}}
          role-session-name: ${{github.run_id}}
          aws-region: ${{env.AWS_REGION}}
          role-duration-seconds: 14400 # 4 hours

      - name: Run Tests
        if: steps.release-please.outputs.pr
        shell: bash
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_OWNER: rancher
          IDENTIFIER: ${{github.run_id}}
          ZONE: ${{secrets.ZONE}}
        run: |
          bash .github/workflows/scripts/run-in-nix-container.sh "bash .github/workflows/scripts/execute-tests.sh"

      - name: 'Comment PR e2e pass'
        if: steps.release-please.outputs.pr
        # https://github.com/actions/github-script/releases
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const scriptPath = `${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/pr-e2e-pass.js`;
            const { default: script } = await import(scriptPath);
            context.payload.pull_request = { number: ${{ fromJson(steps.release-please.outputs.pr).number }} };
            await script({ github, context });
